require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/trashes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Trash. As you add validations to Trash, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Trash.create! valid_attributes
      get trashes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      trash = Trash.create! valid_attributes
      get trash_url(trash)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_trash_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      trash = Trash.create! valid_attributes
      get edit_trash_url(trash)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Trash" do
        expect {
          post trashes_url, params: { trash: valid_attributes }
        }.to change(Trash, :count).by(1)
      end

      it "redirects to the created trash" do
        post trashes_url, params: { trash: valid_attributes }
        expect(response).to redirect_to(trash_url(Trash.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Trash" do
        expect {
          post trashes_url, params: { trash: invalid_attributes }
        }.to change(Trash, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post trashes_url, params: { trash: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested trash" do
        trash = Trash.create! valid_attributes
        patch trash_url(trash), params: { trash: new_attributes }
        trash.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the trash" do
        trash = Trash.create! valid_attributes
        patch trash_url(trash), params: { trash: new_attributes }
        trash.reload
        expect(response).to redirect_to(trash_url(trash))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        trash = Trash.create! valid_attributes
        patch trash_url(trash), params: { trash: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested trash" do
      trash = Trash.create! valid_attributes
      expect {
        delete trash_url(trash)
      }.to change(Trash, :count).by(-1)
    end

    it "redirects to the trashes list" do
      trash = Trash.create! valid_attributes
      delete trash_url(trash)
      expect(response).to redirect_to(trashes_url)
    end
  end
end
